### PR TITLE
Fix parsing logic when line starts with multi word tag

### LINKED ISSUE #7: Multi-word tags at beginning of multi-tag line gain leading underscore
Hey, thanks a lot for writing this! I've just started using Obsidian and being able to import all of my Bear notes to start with is very helpful. I had no problem getting this it to work but I found one little bug.

In [here](https://github.com/bernardoamc/obsidian_bear/blob/7d95e0b1cd00de82cac5162dc3137714fe11833c/lib/obsidian_bear/bear.rb), `extract_tags` does
```ruby
line.split(' #').map { |str| format_tag(str) }
```
and in `format_tag`, 
```ruby
str.chop.gsub(/[^\w\/]/, '_')
```
but if the first tag in `line` was a multiword tag, it still has the leading `#` (because of splitting on _space-#_), which is converted to an underscore.

Since we know it's a multiword tag at that point, I think it should be safe to
```ruby
str.gsub(/#/, '').gsub(/[^\w\/]/, '_')
```
and that looks like it takes care of it:
```ruby
irb(main):061:0> line = "#one two three# #four #five six seven# #eight"
=> "#one two three# #four #five six seven# #eight"
irb(main):062:0> line.split(' #').map { |str| format_tag(str) }
=> ["one_two_three", "four", "five_six_seven", "eight"]
```

but I'm not sure if I've missed an edge case.

(By the way, really appreciate your detailed comments, it was really easy to tell the "why" of the code.)

### PR DESCRIPTION
**Pull request by bernardoamc**
The previous code was generating incorrect tags when the first tag in the line was a multi word tag.

For example:

would become

`['learning', 'ruby']` instead of `['learning_whatever', 'ruby']`

Closes #7

### CODE REVIEW

File: lib/obsidian_bear/bear.rb [hunk 1]
```diff
@@ -44,19 +43,39 @@ def extract_tags
...
+    # 1. If a tag contains "#" in any other position besides the first character
+    #    we know it is a multi word tag
+    # 2. Otherwise we know we have a simple tag
+    #
+    # Based on this we can make the following decisions
+    #
+    # 1. Strip any starting '#'
+    # 2. If we have a multi tag we read until the last '#' and replace spaces
+    #    with underscores
+    # 2. If not we split by space and get the first element since the rest is not
```
Comment (wlonkly) [inline lib/obsidian_bear/bear.rb]:
```suggestion
    # 3. If not we split by space and get the first element since the rest is not
```

Comment (wlonkly) [reply lib/obsidian_bear/bear.rb]: :)

File: lib/obsidian_bear/bear.rb [hunk 2]
```diff
@@ -44,19 +43,39 @@ def extract_tags
...
       else
         str.split.first
       end
+    end
 
-      tag = tag[1..] if tag.start_with?('#')
-      tag
+    def extract_multi_tag(str)
+      last_separator = str.rindex('#')
+      str[...last_separator].gsub(/[^\w\/]/, '_')
```
Comment (wlonkly) [inline lib/obsidian_bear/bear.rb:78]: `...` requires ruby 2.7, but that ought to be fine by now I guess! (I noticed because for some reason my default was 2.6.x.)

**Review by wlonkly — COMMENTED** [review]
lgtm! thanks again for making this available!

File: lib/obsidian_bear/bear.rb (hunk 2 above)
Comment (bernardoamc) [reply lib/obsidian_bear/bear.rb:78]: Yeah, I'm comfortable dropping `2.6.x` since it has reached it's EOL. But I will require the proper version, good call! :)

Comment (bernardoamc) [reply lib/obsidian_bear/bear.rb:78]: I've updated the Gemfile to require `>= 2.7`

**Comment by bernardoamc** [comment]
Thanks again @wlonkly ❤️
